### ISSUE TITLE
About WIKI

### ISSUE THREAD

**Issue by lintangtimur** [Dosugamea/l-api-tips#4]
how you can write some such a 
- Custom Announce
- Custom Music Object/Profile
- JumpToMessage
- Message Footer
in a function and parameter?

**Comment by Dosugamea** [comment]
Like this?

	from akad.ttypes import ChatRoomAnnouncementContents
	from linepy import *
	import json

	client = LINE("AuthToken")

	def makeJump(jump_to,msg_id=1919810):
		return "line://nv/chatMsg?chatId=%s&messageId=%s"%(jump_to,msg_id)

	def addAnnounce(add_to,text,link=None,thumbnail=None):
		if link == None: link = makeJump(add_to)
		client.createChatRoomAnnouncement(add_to,type,ChatRoomAnnouncementContents(displayFields=5,text=text,link=link,thumbnail=thumbnail))
		
	def sendMusic(send_to,music_id,title,artist,thumbnail,link):
		client.sendMessage(send_to, '',
			{'text': title,
			'subText': artist,
			'id': music_id,
			'previewUrl': thumbnail,
			'linkUri': link,
			'i-linkUri': link,
			'a-linkUri': link,
			'i-installUrl': link,
			'a-installUrl': link,
			'a-packageName': 'jp.linecorp.linemusic.android',
			'type': 'mt',
			'countryCode': 'JP',
			'ORGCONTP': 'MUSIC'},
			19)
		
	def sendMessageWithFooter(send_to,text,title="Test",link="",icon=""):
		footer = {
			"AGENT_ICON": icon,
			"AGENT_NAME": title,
			"AGENT_LINK": link
		}
		client.sendMessage(send_to, text, contentMetadata=footer)
		
	def setMusicProfile(music_id,title,artist,thumbnail,link):
		music = {
			"id": music_id,
			"name": title,
			"artistName": artist,
			"imageUrl": thumbnail,
			"url": link,
			"type": "mt",
			"country": "JP"
		}
		pr = client.getProfile()
		pr.musicProfile = json.dumps(music)
		client.updateProfile(pr)

You can find some bots source in github.  
They'll help you if you want more examples.
Please do your best.

**Comment by lintangtimur** [comment]
oh, so that function is already attached in linepy library?

**Comment by Dosugamea** [comment]
createChatRoomAnnouncement getProfile updateProfile sendMessage are already attached to linepy library.
this is just a wrapper to set parametor.
